### PR TITLE
Di 583 v1.2.0

### PR DESCRIPTION
**Pull request by growland2**
- Changed so that reference genome and index are inputted in via one input as a .tar
- Changed to accept more file extensions for the ref genome fasta file (".fasta" and ".fas" are now accepted in addition to ".fa")

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13)

### CODE REVIEW

**Comment by growland2** [comment]
DNA nexus job for successful run https://platform.dnanexus.com/projects/GbBy83Q411z6f01132j4v8ZF/monitor/job/GbFZPv8411z56KKP3B7pxxv5

**Review by Addy81 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @growland2)

___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13#-NjS5_c4D7Pc43EMQ5U7:-NjS5_c4D7Pc43EMQ5U8:bkvoz90) ([raw file](https://github.com/eastgenomics/eggd_somalier_extract/blob/861394b245d1733d2729e76247fe3a27709dec75/README.md#L10)):*
> ```Markdown
> This app is based on https://github.com/brentp/somalier
> 
> Image of workflow)
> ```

I think you need one parethnesis less? It doesn't show in the readme :)

**Review by Addy81 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @growland2)

___
*[`README.md` line 10 at r4](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13#-NjS5_c4D7Pc43EMQ5U7:-NjS5mvb3aZYqHucXc3n:b-220ctg) ([raw file](https://github.com/eastgenomics/eggd_somalier_extract/blob/861394b245d1733d2729e76247fe3a27709dec75/README.md#L10)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I think you need one parethnesis less? It doesn't show in the readme :)
</blockquote></details>

done already i was too quick.

**Review by Addy81 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_extract/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @growland2)

**Pull request merged**
